export interface FooterInfo {
  id: string;
  website_logo: string;
  tab1_name: string;
  tab1_link: string;
  tab2_name: string;
  tab2_link: string;
  tab3_name: string;
  tab3_link: string;
  tab4_name: string;
  tab4_link: string;
  tab5_name: string;
  tab5_link: string;
  tab6_name: string;
  tab6_link: string;
  tab7_name: string;
  tab7_link: string;
  location: string;
  location_link: string;
  phone_number: string;
  email: string;
  facebook_link: string;
  linkedin_link: string;
  instagram_link: string | null;
  x_link: string | null;
  subscribe_title: string;
  subscribe_button: string;
  faq_page_link: string;
  privacy_and_policy_page_link: string;
}
